"""Add branch_name to reports

Revision ID: 11e0281847c8
Revises: 90b5979a4623
Create Date: 2026-06-26 15:13:42.705567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '11e0281847c8'
down_revision: Union[str, Sequence[str], None] = '90b5979a4623'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reports', sa.Column('branch_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'branch_name')
    # ### end Alembic commands ###
